### PR TITLE
Bump bcrypt package version

### PR DESCRIPTION
**Pull request by kpman**

### CODE REVIEW

**Comment by kpman** [comment]
@bsiddiqui Thanks for merging. 
Do you have any plan to release new version on npm?

**Comment by bsiddiqui** [comment]
Yeah I'll release a version today - sorry for the delay

Basil

----
github.com/bsiddiqui
twitter.com/_bsiddiqui
medium.com/@bsiddiqui

**Comment by bsiddiqui** [comment]
@kpman done!

**Comment by kpman** [comment]
@bsiddiqui Cool!

**Pull request merged**
